## Lecture 13

In [1]:
import numpy as np 

In [2]:
a = np.array([[1,1,1],[1,1,1]])
b = np.array([[2,2,2],[2,2,2]])

In [3]:
np.concatenate([a,b],axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [4]:
np.concatenate([a,b],axis=1)

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [5]:
c =  np.arange(20).reshape(4,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
np.split(c, 2, axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [7]:
c =  np.arange(24).reshape(4,6)
print(c)
np.hsplit(c,[2,4])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [8]:
arr = np.arange(1e6)

In [9]:
%timeit sum(arr)

120 ms ± 7.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit np.sum(arr)

2.12 ms ± 333 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
np.arange(4)+5

array([5, 6, 7, 8])

In [12]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [13]:
np.ones((1,5,5)) + np.ones((3,5,1))

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [14]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [15]:
#a)
np.sum(x>3)

np.int64(7)

In [16]:
#b)
np.sum(x==3)

np.int64(3)

In [17]:
#c
np.sum(x[x>3]) #mask


np.int64(43)

In [18]:
print(x[x%2==1])
x[x%2==1].prod()

[5 3 3 7 9 3 5 7]


np.int64(297675)

In [20]:
from my_modules import is_prime

In [21]:

mask = list(map(is_prime, x.flatten()))
x.flatten()[mask].sum()

np.int64(35)

In [22]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [23]:
np.sum(x<6,axis=1)

array([4, 2, 2])

In [24]:
x 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [25]:
np.sort(x,axis = 0)

array([[2, 0, 3, 3],
       [5, 4, 3, 5],
       [7, 9, 7, 6]], dtype=int32)

In [26]:
np.sort(x,axis = 1)

array([[0, 3, 3, 5],
       [3, 5, 7, 9],
       [2, 4, 6, 7]], dtype=int32)

In [27]:
np.sort(x, axis=None)

array([0, 2, 3, 3, 3, 4, 5, 5, 6, 7, 7, 9], dtype=int32)

In [28]:
np.sort(x, axis=None).reshape(3,4)

array([[0, 2, 3, 3],
       [3, 4, 5, 5],
       [6, 7, 7, 9]], dtype=int32)

In [29]:
print(x)
np.sort(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[0, 3, 3, 5],
       [3, 5, 7, 9],
       [2, 4, 6, 7]], dtype=int32)

In [30]:
y = x.flatten()
y 

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6], dtype=int32)

In [31]:
print(np.argsort(y))
y[np.argsort(y)]

[ 1  8  3  2  6  9  0  7 11  4 10  5]


array([0, 2, 3, 3, 3, 4, 5, 5, 6, 7, 7, 9], dtype=int32)

In [32]:
x 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [33]:
np.argsort(x)[:,0]

array([1, 2, 0])

In [34]:
np.sort(x,)

array([[0, 3, 3, 5],
       [3, 5, 7, 9],
       [2, 4, 6, 7]], dtype=int32)

In [39]:
x= np.arange(10)
x[range(1,10,2)]


array([1, 3, 5, 7, 9])

In [50]:
y = np.arange(1,10).reshape(3,3)
print(y)
print(y[[0,1,2],[0,1,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [52]:
z = np.arange(10,100,10)
print(z[range(0,10,2)])

[10 30 50 70 90]


In [54]:
a = np.random.randint(0,100,size=10)
print(a)

[75 68  6 68 47  3 76 52 78 15]


In [55]:
np.sort(a)

array([ 3,  6, 15, 47, 52, 68, 68, 75, 76, 78], dtype=int32)

In [56]:
np.argsort(a)

array([5, 2, 9, 4, 7, 1, 3, 0, 6, 8])

In [57]:
b = np.random.randint(0,100,(3,3))
print(b)

[[20 99 58]
 [23 79 13]
 [85 48 49]]


In [58]:
#row
np.sort(b,axis=1)

array([[20, 58, 99],
       [13, 23, 79],
       [48, 49, 85]], dtype=int32)

In [59]:
#column
np.sort(b,axis=0)


array([[20, 48, 13],
       [23, 79, 49],
       [85, 99, 58]], dtype=int32)

In [61]:
c = np.random.randint(100,size=20)
print(c)

[41 35 64 95 69 94  0 50 36 34 48 93  3 98 42 77 21 73  0 10]


In [63]:
np.sort(c)[::-1]

array([98, 95, 94, 93, 77, 73, 69, 64, 50, 48, 42, 41, 36, 35, 34, 21, 10,
        3,  0,  0], dtype=int32)

In [35]:
np.random.seed(0)
A = np.random.randint(100, size=(3,4,6))
print(A)

[[[44 47 64 67 67  9]
  [83 21 36 87 70 88]
  [88 12 58 65 39 87]
  [46 88 81 37 25 77]]

 [[72  9 20 80 69 79]
  [47 64 82 99 88 49]
  [29 19 19 14 39 32]
  [65  9 57 32 31 74]]

 [[23 35 75 55 28 34]
  [ 0  0 36 53  5 38]
  [17 79  4 42 58 31]
  [ 1 65 41 57 35 11]]]
